### ISSUE TITLE
images src not found

### ISSUE THREAD

**Issue by sfwnisme** [Moamal-2000/boycott-them#1]
First of all, I encourage you for this great project

ISSUE: A lot of the images have incorrect pathnames
![image](https://github.com/Moamal-2000/boycott-them/assets/92028514/84cde5ba-acbb-414e-be5e-6eb99cd53375)

**Comment by Moamal-2000** [comment]
Hey @sfwnisme, Thank you for supporting

yeah I know all these images still missing
I'm working on it now to get replacement product images from the internet
it will take time to get them all since I'm working on this project alone now

I have to do some steps to make those images on the website 
which is a lot of work for me but I'm making some progress.
- first of all, searching for the replacement product name
- then get a good image of the replacement product
- sometimes I have to convert the extension's image file to PNG if it is an AVIF image
- then remove the background image of the product
- then make the image smaller in size
- the last step is to convert it into a WEBP image and add it to the project
